[profile.default]
libs = ["lib"]
out = "out"
src = "src"

[invariant]
depth = 128
fail_on_revert = false
runs = 128
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
